name: PHPUnit Tests

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - '*'  
      
jobs:
  test-with-mysql:
    name: PHP ${{ matrix.php }}
    uses: syy25/wordpress-develop/.github/workflows/phpunit-tests-run.yml@trunk
    permissions:
      contents: read
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        db-type: [ 'mysql' ]
        db-version: [ '5.7', '8.0' ]
        multisite: [ false, true ]
        memcached: [ false ]

        include:
          - os: ubuntu-latest
            php: '7.4'
            db-type: 'mysql'
            db-version: '5.7'
            multisite: false
            memcached: true
          - os: ubuntu-latest
            php: '7.4'
            db-type: 'mysql'
            db-version: '5.7'
            multisite: true
            memcached: true
          # Report test results to the Host Test Results.
          - os: ubuntu-latest
            php: '7.4'
            db-type: 'mysql'
            db-version: '5.7'
            multisite: false
            memcached: false
            report: true
    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      phpunit-config: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}
      report: ${{ matrix.report || false }}

  #
  # Creates a PHPUnit test job for each PHP/MariaDB combination.
  #
  test-with-mariadb:
    name: PHP ${{ matrix.php }}
    uses: syy25/wordpress-develop/.github/workflows/phpunit-tests-run.yml@trunk
    permissions:
      contents: read
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        db-type: [ 'mariadb' ]
        db-version: [ '10.4', '10.6', '10.11', '11.0' ]
        multisite: [ false, true ]
        memcached: [ false ]

        include:
        # Include jobs for PHP 7.4 with memcached.
        - os: ubuntu-latest
          php: '7.4'
          db-type: 'mariadb'
          db-version: '11.0'
          multisite: false
          memcached: true
        - os: ubuntu-latest
          php: '7.4'
          db-type: 'mariadb'
          db-version: '11.0'
          multisite: true
          memcached: true
    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      phpunit-config: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}
      report: ${{ matrix.report || false }}
